[package]
name = "tracer"
version = "0.2.0"
authors = [
    # author of the original riscv-rust codebase
    "Takahiro <hogehoge@gachapin.jp>",
    # authors of the modifications for Jolt
    "Michael Zhu <mzhu@a16z.com>",
    "Sam Ragsdale <sragsdale@a16z.com>",
    "Noah Citron <ncitron@a16z.com>",
]
description = "RISC-V emulator for Jolt"
license = "MIT"
homepage = "https://github.com/a16z/jolt/README.md"
repository = "https://github.com/a16z/jolt"
edition = "2021"

[dependencies]
fnv = "1.0.7"
object = "0.32.1"
tracing = "0.1.37"

common = { path = "../common" }
